---
# tasks file for batyam

- name: install openshift package for the 'k8s' module
  pip:
    name: openshift

- name: Create configmap batyam-gerrit-identity-path-envvar
  k8s:
    api_key: "{{ batyam_ocp_token }}"
    host: "{{ batyam_ocp_host }}"
    state: "{{ batyam_deploy_state }}"
    # TODO: make batyam ocp connection use CACERT file
    #ca_cert: "{{ batyam_ca_cert }}"
    name: batyam-gerrit-identity-path-envvar
    namespace: "{{ batyam_ocp_resources_namespace }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: batyam-gerrit-identity-path-envvar
        namespace: "{{ batyam_ocp_resources_namespace }}"
      data:
        # TODO: set data to actual data when secret is also created
        GERRIT_IDENTITY_FILE: /tmp/gerrit-key

- name: clone a private repository
  git:
    repo: "{{ batyam_configs_repo }}"
    key_file: "{{ batyam_configs_repo_key }}"
    dest: "{{ batyam_configs_repo_dir }}"
    version: "{{ batyam_configs_repo_version }}"

- name: create batyam-repos-volume configmap
  k8s:
    api_key: "{{ batyam_ocp_token }}"
    host: "{{ batyam_ocp_host }}"
    state: "{{ batyam_deploy_state }}"
    name: batyam-repos-volume
    namespace: "{{ batyam_ocp_resources_namespace }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: batyam-repos-volume
        namespace: "{{ batyam_ocp_resources_namespace }}"
      data:
        config.yaml: "{{ lookup('file', batyam_configs_repo_dir + '/config.yaml') }}"
