# Generated by Django 2.1.15 on 2020-08-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('OP', 'Open'), ('CD', 'Closed')], max_length=2)),
                ('vendor', models.CharField(choices=[('GH', 'Github'), ('GL', 'Gitlab'), ('GR', 'Gerrit')], max_length=2)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('github_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('gitlab_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('gerrit_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='codecontribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contributor'),
        ),
        migrations.AddField(
            model_name='codecontribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Project'),
        ),
    ]
